name: oppgave 15
#on: [push, workflow_dispatch]
on:
    push:
      paths:
        .github/workflows/oppgave_15.yml
jobs:
  job1:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1